Docs contributing guide 2
CeruleanCodersComm/.github pull request #3
Opened 2021-12-29 05:31 UTC by Abhirv08

### Describe the changes you've made

Updated Readme.md

## How has this been tested?

## Checklist

- [ ] I have made changes to the documentation.

## Additional Information

 
## Code of Conduct

- [ ] I agree to follow this project's [Code of Conduct](https://github.com/CeruleanCodersComm/.github/blob/main/CODE_OF_CONDUCT.md)

2021-12-29 05:32 UTC, Abhirv08 commented
Please add review section, everything else has been solved.

2021-12-29 11:33 UTC, krishguptadev requested changes
The guide you added should be a in a file named `CONTRIBUTING.md`

2021-12-29 13:30 UTC, Abhirv08 commented
Okay, i will make the changes

2021-12-29 13:30 UTC, Abhirv08 commented
Okay, i will make the changes

2021-12-29 13:31 UTC, Abhirv08 commented
Okay, i will make the changes

2021-12-29 13:39 UTC, Abhirv08 commented
Okay, i will change these

2021-12-29 13:49 UTC, Abhirv08 commented
@krishguptadev I have added contributing.md and added the sections.

2021-12-29 15:38 UTC, krishguptadev requested changes

2021-12-29 15:38 UTC, krishguptadev commented on README.md
> +
```suggestion
```

2021-12-29 15:38 UTC, krishguptadev commented on contributing.md
> +<br/>
```suggestion

```

2021-12-29 15:38 UTC, krishguptadev commented on contributing.md
> +This section guides you through submitting a bug report. Following these guidelines helps maintainers and the community understand your report 📝, reproduce the behavior 💻 💻, and find related reports.
```suggestion
This section guides you through submitting a bug report. Following these guidelines helps maintainers and the community understand your report 📝, reproduce the behaviour 💻 💻, and find related reports. 🔎
```

2021-12-29 15:38 UTC, suitupstan commented on contributing.md
> +Since the new GitHub Issue forms we only suggest you to include most information possible. But you can also **Perform a [cursory search](https://github.com/CeruleanCodersComm/.github/issues)** to see
```suggestion
Since the new GitHub Issue forms, we only suggest you include the most information possible. But you can also **Perform a [cursory search](../../../issues)** to see if the enhancement has already been suggested. If it has, adds a comment to the existing issue instead of opening a new one.
```

2021-12-29 15:38 UTC, krishguptadev commented on contributing.md
> +Bugs are tracked as github [issues](https://github.com/CeruleanCodersComm/.github/issues). After you've determined which repository your bug is related to, create an issue on that repository.
```suggestion
Bugs are tracked as github [issues](../../../issues). After you've determined which repository your bug is related to, create an issue on that repository.
```

2021-12-29 15:38 UTC, krishguptadev commented on contributing.md
> +**1.** Fork [this](https://github.com/CeruleanCodersComm/.github) repository. Click on the <a  href="https://github.com/CeruleanCodersComm/.github"><img  src="https://img.icons8.com/fluency/30/000000
```suggestion
**1.** [Fork](../../../fork) this repository.
```

2021-12-30 09:02 UTC, Abhirv08 commented
@krishguptadev i have modified as per changes shown by you. Please review it.

2021-12-31 05:37 UTC, krishguptadev commented on contributing.md
> +This section guides you through submitting a bug report. Following these guidelines helps maintainers and the community understand your report 📝, reproduce the behaviour 💻 💻, and find related reports
```suggestion

This section guides you through submitting a bug report. Following these guidelines helps maintainers and the community understand your report 📝, reproduce the behaviour 💻 💻, and find related reports. 🔎
```

2021-12-31 05:38 UTC, merged